// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhMzbj8_K-SHAALFEXAKNqbaZQk7pw_08',
    appId: '1:598124076737:web:298163be604f2b4cd57e40',
    messagingSenderId: '598124076737',
    projectId: 'flutter-coffee-shop-cc736',
    authDomain: 'flutter-coffee-shop-cc736.firebaseapp.com',
    storageBucket: 'flutter-coffee-shop-cc736.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsf3hxkqKHBZP5lAemwT4Y1tJiOb145-g',
    appId: '1:598124076737:android:ddd7d66cfdfd8e5dd57e40',
    messagingSenderId: '598124076737',
    projectId: 'flutter-coffee-shop-cc736',
    storageBucket: 'flutter-coffee-shop-cc736.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9NxOP1nThE4HxF0EVhBPjGI02xTGXDSQ',
    appId: '1:598124076737:ios:48594a078191f7afd57e40',
    messagingSenderId: '598124076737',
    projectId: 'flutter-coffee-shop-cc736',
    storageBucket: 'flutter-coffee-shop-cc736.appspot.com',
    iosClientId: '598124076737-226122jg32fd6f3uji0qfmcrtbuaflkg.apps.googleusercontent.com',
    iosBundleId: 'com.example.coffeeApp',
  );
}
