// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1BfRGKX-HWaEp-dMhjz5167eyuKUTffg',
    appId: '1:659993229138:web:d93e71bde4556663516c8b',
    messagingSenderId: '659993229138',
    projectId: 'coffee-shop-fb1c5',
    authDomain: 'coffee-shop-fb1c5.firebaseapp.com',
    storageBucket: 'coffee-shop-fb1c5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA63pcdd4onETQ9fuOq7jlA9D7lYOjhDdM',
    appId: '1:659993229138:android:6c969b9b02b7506a516c8b',
    messagingSenderId: '659993229138',
    projectId: 'coffee-shop-fb1c5',
    storageBucket: 'coffee-shop-fb1c5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgpzHixknB-19_4fk9-NC_f_IpuZmO5Zs',
    appId: '1:659993229138:ios:292d709e23fe6c5c516c8b',
    messagingSenderId: '659993229138',
    projectId: 'coffee-shop-fb1c5',
    storageBucket: 'coffee-shop-fb1c5.appspot.com',
    iosClientId: '659993229138-h4fgg9es6r0gd5jfm9teqslqdu9o90sj.apps.googleusercontent.com',
    iosBundleId: 'com.example.coffeeApp',
  );
}
